feat(header): disable routes while app are synchronizing
indec-it/react-native-commons pull request #83
Opened 2019-07-22 17:03 UTC by juanlopez1

2019-07-22 17:10 UTC, mdumrauf commented on src/components/Header/index.js
> +        requestFetchToken: PropTypes.func.isRequired,
No me cierra que el Header quede acoplado a la sincro. Qué opinás @maximilianoforlenza ?

2019-07-22 17:34 UTC, juanlopez1 commented on src/components/Header/index.js
> +        requestFetchToken: PropTypes.func.isRequired,
El `Header` pide el token, no por la sincro, sino para mostrar o no las rutas, por lo que en el login no aparecerian.

2019-07-22 17:35 UTC, maximilianoforlenza commented on src/components/Header/Routes.js
> +                {...{route, onDisable, onLogout}}
agrega el `disabled` aca

2019-07-22 18:18 UTC, maximilianoforlenza commented on src/components/Header/index.js
> +        requestFetchToken: PropTypes.func.isRequired,
en esta parte no hay nada acoplado a la sincro

2019-07-22 18:24 UTC, maximilianoforlenza requested changes

2019-07-22 18:24 UTC, maximilianoforlenza commented on src/components/Header/index.js
> +        running: state.sync.running
esto si me parece un poco acoplado, ya que dependes si o si tener un `running` en el reducer de sync, y si lo quisiera deshabilitar teniendo un running en otro lado no podria,  te diria que se lo pases por prop en ves de tomarlo del store

2019-07-22 21:39 UTC, juanlopez1 commented on src/components/Header/index.js
> +        running: state.sync.running
Listo

2019-07-22 21:40 UTC, juanlopez1 commented on src/components/Header/Routes.js
> +                {...{route, onDisable, onLogout}}
Listo

2019-07-22 22:27 UTC, maximilianoforlenza commented on src/components/Header/index.js
> +        working: PropTypes.bool
hacele rename a `disabled` asi queda mas generico

2019-07-23 13:01 UTC, maximilianoforlenza commented on src/components/Header/index.js
> +                {showModal && modalType === modalTypes.SYNC_ALERT && (
podrias evitar repetir el `showModal`
```js
   {showModal && (
                    <Fragment>
                        {modalType === modalTypes.SYNC_ALERT && (
                            <AlertModal
                                onDismiss={() => this.handleCloseModal()}
                                text="Hasta que no termine este proceso, no puede continuar."
                                title="Sincronización"
                            />
                        )}
                        {modalType === modalTypes.CLOSE_SESSION && (
                            <ConfirmModal
                                onDismiss={() => this.handleCloseModal()}
                                onAccept={() => this.signOut()}
                                text={getLogoutMessage(routes)}
                                title="Cerrar Sesión"
                            />
                        )}
                    </Fragment>
                )}
```
incluso te diria que esto lo muevas a un nuevo componente

2019-07-23 22:49 UTC, juanlopez1 commented on src/components/Header/index.js
> +        working: PropTypes.bool
Listo

2019-07-23 23:10 UTC, juanlopez1 commented on src/components/Header/index.js
> +                {showModal && modalType === modalTypes.SYNC_ALERT && (
Listo

2019-07-23 23:33 UTC, maximilianoforlenza approved these changes

2019-07-24 10:40 UTC, maximilianoforlenza commented
@mdumrauf lo tenes asignado vos.

2019-07-24 11:31 UTC, merged

2019-07-24 11:32 UTC, maximilianoforlenza commented
Se mergea debido a que se necesita deployar.